Accueil:
    path: /accueil
    controller: App\Controller\AccueilController::accueil

Connexion:
    path: /connexion
    controller: App\Controller\ConnexionController:connexion

Profil:
    path: /profil
    controller: App\Controller\ProfilController:profil

AfficherProfil:
  path: /profil/afficherProfil/{participant}
  controller: App\Controller\ProfilController:afficherProfil

NouveauProfil:
    path: /profil/nouveauProfil
    controller: App\Controller\ProfilController:nouveauProfil

ModifierProfil:
    path: /profil/modifierProfil
    controller: App\Controller\ProfilController:modifierProfil

Sortie:
    path: /sortie
    controller: App\Controller\SortieController:sortie

NouvelleSortie:
  path: /sortie/nouvelleSortie
  controller: App\Controller\SortieController:nouvelleSortie