Connexion:
    path: /connexion
    controller: App\Controller\ConnexionController:connexion

Deconnexion:
    path: /deconnexion
    controller: App\Controller\ConnexionController:deconnexion

Accueil:
    path: /accueil
    controller: App\Controller\AccueilController::accueil

Profil:
    path: /profil
    controller: App\Controller\ProfilController:profil

NouveauProfil:
    path: /profil/nouveauProfil
    controller: App\Controller\ProfilController:nouveauProfil

Sortie:
    path: /sortie
    controller: App\Controller\SortieController:sortie